---
- name: Install and setup zabbix agents
  hosts: monitored
  vars_files:
    - vars/zabbix.yml
    - vars/agent.yml

  tasks:
    - include_role:
        name: roles/zabbix-agent-rhel7
      when: "ansible_facts.os_family == 'RedHat'"

    - name: Copy userparameter files
      copy:
        src: "userparameter/"
        dest: "/etc/zabbix/zabbix_agentd.d/"
      notify: restart zabbix-agent
